config/routes.rb
Producer::Application.routes.draw do

  resources :posts, :only => [:index, :show] do
    resources :comments, :only => [:index, :create]
  end

  scope '/admin' do
    devise_for :users, :controllers => {
      :sessions => "admin/sessions",
      :passwords => "admin/passwords"
    }    
  end

  namespace :admin do
    resources :users, :except => [:show]
    resources :images
    resources :categories, :except => [:show]
    resources :inquiries, :except => [:new, :create]
    resources :posts do 
      get :images, :on => :collection
    end
  end

  resources :inquiries, 
    :only => [:new, :create], 
    :path => "contact"

  match '/home'   => "pages#index",  :as => :home
  match '/prices' => "pages#prices", :as => :prices
  match '/tour'   => "pages#tour",   :as => :tour

  root :to => 'pages#index'
  get "pages/index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  
  belongs_to :author, 
    :class_name => "User", 
    :foreign_key => "author_id"

  default_scope :order => "published_at DESC"
  delegate :full_name, :to => :author, :prefix => true

  validates_presence_of   :title, :body, :author, :published_at
  validates_uniqueness_of :slug
  validates_inclusion_of :draft, :in => [true, false]
  validates_associated :author

  before_validation :generate_slug

  def self.published
    where("draft = ? AND published_at < ?", false, Time.current)     
  end
  
  def self.search(terms) 
    where("title LIKE :t OR body LIKE :t", :t => "%#{terms}%")
  end
  
  def to_param
    "#{id}-#{slug}"
  end
  
protected

  def generate_slug
    self.slug = self.title unless self.slug.present?
    self.slug = self.slug.parameterize
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :load_resources, :only => %w(new create edit update)

  menu_item :posts

  def index
    @posts = Post.all
    respond_with @posts
  end

  def show
    @post = Post.find(params[:id])
    respond_with @post do |format|
      format.html { render :layout => "application" }
    end
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with @post, :location => admin_posts_path
  end

  def update
    @post = Post.find(params[:id])
    flash[:notice] = 'Post was successfully updated.' if @post.update_attributes(params[:post])
    respond_with @post, :location => edit_admin_post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_with @post, :location => admin_posts_path
  end

  def images
    @images = paginated_images
  end

protected

  def load_resources
    @authors = User.all
    @categories = Category.all
    @images = paginated_images
  end

  def paginated_images
    Image.paginate(:page => params[:page], :per_page => 4)    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :categories

  def index
    @posts = Post.scoped
    @posts = @category.posts if @category.present?        
    @posts = @posts.search(params[:search]) if params[:search].present?
    @posts = @posts.published
  
    respond_with @posts do |format|
      format.atom
    end
  end

  def show
    @post = Post.find(params[:id])
    respond_with @post
  end

protected

  def categories
    @category = Category.find(params[:category_id]) if params[:category_id].present?
    @categories = Category.all
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def gravatar_image_tag(email, html_options = {})
    email = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/#{email}?size=48", html_options
  end

  def comment_author(name, url="")
    name = "Anonymous Coward" unless name.present?
    url.present? ? link_to(name, url, :target => "_blank") : name
  end

end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>

  <%= error_messages_for @post %>

  <div id="body">
    <div class="field">
      <%= f.label :author_id, t(".author") %>
      <%= f.collection_select :author_id, @authors, :id, :full_name %>
    </div>

    <div class="field">
      <%= f.text_field :title, :placeholder => ta(Post, :title), :class => "title" %>
    </div>

    <div class="field">
      <%= f.text_area :excerpt, :placeholder => ta(Post, :excerpt), :rows => 5, :cols => 70 %>
    </div>

    <div class="field">
      <%= f.text_area :body, :placeholder => ta(Post, :body), :rows => 30, :cols => 70 %>
    </div>

    <div class="field">
      <%= f.check_box :draft %>
      <%= f.label :draft %>
    </div>

    <hr class="thick" />

    <p>
      <%= f.submit :class => "button" %> 
      <%= t "or" %>
      <%= link_to t("cancel"), admin_posts_path %>
    </p>
  </div>

  <div id="sidebar">
    <%= section t(".categories") do %>
      <ul class="categories-field">
        <% @categories.each do |c| %>
          <li><%= check_box_tag "post[category_ids][]", c.id, @post.categories.include?(c) %> <%= c.name %></li>
        <% end %>
      </ul>
      <div class="bar">
        <%= link_to_new Category, new_admin_category_path, :class => "button right" %>
      </div>
      <br/>
    <% end %>

    <hr/>

    <%= section  do %>
      <div class="field">
        <%= f.label :published_at %><br/>
        <%= f.date_select :published_at, :use_short_month => true %>
      </div>
    <% end %>

    <hr/>

    <%= section  do %>
      <div class="field">
        <%= f.label :slug, t(".slug") %><br/>
        <%= f.text_field :slug, :size => 38 %>
      </div>
    <% end %>
    
    <hr/>

    <%= section t(".media") do %>
      <div id="media" class="media">
        <%= render :partial => "image", :collection => @images %>
      </div>

      <p>
        <%= link_to "load more images",
              images_admin_posts_path(:page => @images.next_page),
              :remote => true,
              :id => "more-images",
              :class => "button" %>

        <%= image_tag "loader.gif", 
              :id => "images-loading", 
              :class => "middle loading" %>
      </p>
    <% end %>
    
    <br/>   
  </div>

<% end %>

<% content_for :bottom do%>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      
      var toggleLoading = function() { 
        $("#images-loading").toggle();
      };
      
      $("document")
        .bind("ajax:loading", toggleLoading)
        .bind("ajax:complete", toggleLoading);
      
      $(".media").insertTextileImageTo("#post_body");
      
    });
  </script>
<% end %>

app/views/admin/posts/_image.html.erb
<%= link_to image_tag(image.document.url(:thumb)) , 
      image.document.url, 
      :target => "_blank" %>

app/views/admin/posts/edit.html.erb
<h2>
  <%=t ".title" %>
  <%= link_to 'Preview', [:admin, @post], :class => "button right", :target => "_blank" %>
</h2>

<%= render 'form' %>

app/views/admin/posts/images.js.erb
$("#media").append("<%= escape_javascript(render :partial => "image", :collection => @images) %>");

<% unless @images.total_pages == @images.current_page %>
  $("#more-images").attr("href", "<%= images_admin_posts_path(:page => @images.next_page) %>");
<% else %>
  $("#more-images").hide();
<% end %>

app/views/admin/posts/index.html.erb
<h2>Posts</h2>

<% if @posts.present? %>
<ul class="list">
  <% @posts.each do |post| %>
    <%= content_tag_for :li, post, :class => cycle(:odd, :even) do %>
      <%= link_to post.title.titleize, [:admin, post] %>

      <div class="right">
        <%= link_to_edit [:edit, :admin, post] %>,
        <%= link_to_destroy [:admin, post] %>
      </div>
    <% end %>
  <% end %>
</ul>
<% else %>
  <p><%=t "empty", :collection => "posts" %></p>
<% end %>

<hr class="thick" />

<div class="bar">
  <div class="right">
    <%= link_to_new Post, new_admin_post_path, :class => "button" %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<h2><%=t ".title" %></h2>


<%= render 'form' %>

app/views/admin/posts/show.html.erb
<div id="column1">
  <h2><%= @post.title %></h2>

  <div id="post">
    <%= textilize @post.body %>
  </div>
</div>