config/routes.rb
Producer::Application.routes.draw do

  resources :posts, :only => [:index, :show] do
    resources :comments, :only => [:index, :create]
  end

  scope '/admin' do
    devise_for :users, :controllers => {
      :sessions => "admin/sessions",
      :passwords => "admin/passwords"
    }    
  end

  namespace :admin do
    resources :users, :except => [:show]
    resources :images
    resources :categories, :except => [:show]
    resources :inquiries, :except => [:new, :create]
    resources :posts do 
      get :images, :on => :collection
    end
  end

  resources :inquiries, 
    :only => [:new, :create], 
    :path => "contact"

  match '/home'   => "pages#index",  :as => :home
  match '/prices' => "pages#prices", :as => :prices
  match '/tour'   => "pages#tour",   :as => :tour

  root :to => 'pages#index'
  get "pages/index"

end

app/models/image.rb
class Image < ActiveRecord::Base
  
  validates_presence_of :title

  default_scope :order => "created_at DESC"
  
  has_attached_file :document, styles: {
    medium: "300x300#",
    thumb: "50x50#"
  }

  validates_attachment_presence     :document
  validates_attachment_size         :document, 
    :less_than => 5.megabyte

  validates_attachment_content_type :document, 
    :content_type => %w(image/png image/jpeg image/gif image/tiff)

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  menu_item :images

  def index
    @images = Image.paginate(:page => params[:page], :per_page => 2)
    respond_with @images
  end

  def new
    @image = Image.new
    respond_with @image
  end

  def edit
    @image = Image.find(params[:id])
  end

  def show
    @image = Image.find(params[:id])
    respond_with @image
  end

  def create
    @image = Image.new(params[:image])
    flash[:notice] = 'Image was successfully created.' if @image.save
    respond_with @image, :location => [:admin, @image]
  end

  def update
    @image = Image.find(params[:id])
    flash[:notice] = 'Image was successfully updated.' if @image.update_attributes(params[:image])
    respond_with @image, :location => [:admin, @image]
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    respond_with @image, :location => admin_images_path
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image]  do |f| %>
  <%= error_messages_for @image %>

  <div class="field">
    <%= f.text_field :title, :placeholder => "Title" %>
  </div>

  <div class="field">
    <%= f.file_field :document %>
  </div>

  <hr class="thick" />

  <p>
    <%= f.submit :class => "button" %> or 
    <%= link_to "cancel", admin_images_path %>
  </p>
<% end %>

app/views/admin/images/edit.html.erb
<h2>Editing Image</h2>

<%= render 'form' %>

app/views/admin/images/index.html.erb
<h2>images</h2>

<%- if @images.present? -%>

  <table class="grid">
    <% @images.each do |image| %>
      <%= content_tag_for :tr, image, :class => cycle(:odd, :even) do %>
        <td style="width:10%">
          <%= link_to image_tag(image.document.url(:thumb), :class => "middle"), [:admin, image] %>
        </td>
        <td>
          <%= link_to image.title, [:admin, image] %>
        </td>
        <td style="width:15%; text-align:right;">
          <%= link_to_edit [:edit, :admin, image] %>
          <%= link_to_destroy [:admin, image] %>
        </td>
      <% end %>
    <% end %>
  </table>

<%- else -%>
  <p>You don't have any image yet.</p>
<%- end -%>

<hr class="thick" />

<div class="bar">
  <div class="left">
    <%= will_paginate @images %>
  </div>
  
  <div class="right">
    <%= link_to 'New image', new_admin_image_path, :class => "button" %>
  </div>
</div>

app/views/admin/images/new.html.erb
<h2>New image</h2>

<%= render 'form' %>

app/views/admin/images/show.html.erb
<div class="image">
  <div class="preview">
    <%= link_to image_tag(@image.document.url(:medium)), @image.document.url, :target => "_blank" %>
  </div>

  <div class="info">
    <p>
      <b>Title:</b>
      <%= @image.title %>
      <span class="hint">
        (<%= number_to_human_size @image.document_file_size %>)
        <%= @image.document_content_type %>
      </span>
    </p>

    <hr class="thick" />

    <p>
      <%= link_to 'Edit', edit_admin_image_path(@image), :class => "button" %>
      <%= link_to 'Back', admin_images_path, :class => "button" %>
    </p>
  </div>
</div>