config/routes.rb
Producer::Application.routes.draw do

  resources :posts, :only => [:index, :show] do
    resources :comments, :only => [:index, :create]
  end

  scope '/admin' do
    devise_for :users, :controllers => {
      :sessions => "admin/sessions",
      :passwords => "admin/passwords"
    }    
  end

  namespace :admin do
    resources :users, :except => [:show]
    resources :images
    resources :categories, :except => [:show]
    resources :inquiries, :except => [:new, :create]
    resources :posts do 
      get :images, :on => :collection
    end
  end

  resources :inquiries, 
    :only => [:new, :create], 
    :path => "contact"

  match '/home'   => "pages#index",  :as => :home
  match '/prices' => "pages#prices", :as => :prices
  match '/tour'   => "pages#tour",   :as => :tour

  root :to => 'pages#index'
  get "pages/index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, foreign_key: "author_id"

  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, 
    :remember_me, :first_name, :last_name
  
  validates_presence_of :first_name, :last_name
  
  def full_name
    [first_name, last_name].join(" ")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  menu_item :users

  def index
    @users = User.all
    respond_with @users
  end

  def new
    @user = User.new
    respond_with @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    flash[:notice] = 'User was successfully created.' if @user.save
    respond_with @user, :location => [:admin, :users]
  end

  def update
    @user = User.find(params[:id])
    flash[:notice] = 'User was successfully updated.' if @user.update_attributes(params[:user])
    respond_with @user, :location => [:admin, :users]
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user, :location => [:admin, :users]
  end

end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

  <%= error_messages_for @user %>

  <p><%= f.text_field :full_name, :placeholder => "full name" %></p>
  <p><%= f.text_field :email, :placeholder => "email" %></p>
  <p><%= f.password_field :password, :placeholder => "password" %></p>
  <p><%= f.password_field :password_confirmation, :placeholder => "password confirmation" %></p>

  <hr class="thick" />

  <p>
    <%= f.submit :class => "button" %>
    or <%= link_to "cancel", admin_users_path %>
  </p>

<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit user</h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h2>Users</h2>

<ul class="list">
  <% @users.each do |user| %>
    <%= content_tag_for :li, user, :class => cycle(:odd, :even) do %>
      <%= link_to "#{user.full_name} (#{user.email})", [:admin, user] %>

      <div class="right">
        <%= link_to_edit [:edit, :admin, user] %>
        <%= link_to_destroy [:admin, user] unless current_user == user %>
      </div>
    <% end %>
  <% end %>
</ul>

<hr class="thick" />

<div class="bar">
  <div class="right">
    <%= link_to 'New user', new_admin_user_path, :class => "button" %>
  </div>
</div>

app/views/admin/users/new.html.erb
<h2>New user</h2>

<%= render 'form' %>