config/routes.rb
Producer::Application.routes.draw do

  resources :posts, :only => [:index, :show] do
    resources :comments, :only => [:index, :create]
  end

  scope '/admin' do
    devise_for :users, :controllers => {
      :sessions => "admin/sessions",
      :passwords => "admin/passwords"
    }    
  end

  namespace :admin do
    resources :users, :except => [:show]
    resources :images
    resources :categories, :except => [:show]
    resources :inquiries, :except => [:new, :create]
    resources :posts do 
      get :images, :on => :collection
    end
  end

  resources :inquiries, 
    :only => [:new, :create], 
    :path => "contact"

  match '/home'   => "pages#index",  :as => :home
  match '/prices' => "pages#prices", :as => :prices
  match '/tour'   => "pages#tour",   :as => :tour

  root :to => 'pages#index'
  get "pages/index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag "admin" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="wrapper">
    <div id="header">
      <% if user_signed_in? %>
        <div id="main-nav">
          <%= menu do |m| %>
            <%= m.dashboard 'Dashboard', "#" %>
            <%= m.posts 'Posts', admin_posts_path %>
            <%= m.assets 'Assets', admin_images_path %>
            <%= m.inquiries 'Inquiries', admin_inquiries_path %>
            <%= m.users 'Users', admin_users_path %>
          <% end %>
        </div>

        <div id="user-bar">
          <%= link_to "Logout", destroy_user_session_path, :method => "delete" %>
        </div>
      <% end %>
    </div>

    <div id="content-wrapper">
      <div id="content">
        <div class="in">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <%= yield :bottom %>
</body>
</html>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  
  <%= yield :head %>
</head>

<body id="<%= body_css_id %>">

  <div id="wrapper">
    <div id="header">
      <div id="logo">
        <%= image_tag "logo_header.png", :class => "middle" %>
      </div>

      <div id="main-nav">
        <%= menu do |m| %>
          <%= m.home root_path do %>
            HOME <br/><span>DISCOVER OUR <br/> AWESOME PRODUCT</span>
          <% end %>

          <%= m.tour tour_path do %>
            TOUR <br/><span>DISCOVER WHY IT'LL <br/> MAKE YOUR LIFE BETTER</span>
          <% end %>

          <%= m.posts posts_path do %>
            BLOG <br/><span>NEWS, TIPS AND OUR <br/> RANDOM THOUGHTS</span>
          <% end %>

          <%= m.contact new_inquiry_path do %>
            CONTACT <br/><span>YOU'RE NOT ALONE <br/> GET IN TOUCH</span>
          <% end %>

          <%= m.prices prices_path do %>
            PRICE <br/><span>SMALL AMOUNT <br/> FOR A BIG BENEFIT</span>
          <% end %>
        <% end %>
      </div>
    </div>

    <div id="content">
      <%= flash_messages %>

      <%= yield %>
    </div>

    <div id="footer">
      <div id="footer-nav">
        <ul>
          <li><a>HOME</a></li>
          <li><a>TOUR</a></li>
          <li><a>BLOG</a></li>
          <li><a>FAQ</a></li>
          <li><a>CONTACT</a></li>
          <li><a>PRICE</a></li>
        </ul>
      </div>
    </div>
  </div>

  <%= yield :bottom %>
</body>
</html>